db.url=jdbc:postgresql://localhost:5432/bookdb
db.username=YOUR_USERNAME
db.password=YOUR_PASSWORD
db.driver=org.postgresql.Driver

hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.hbm2ddl.auto=validate
hibernate.show_sql=true
hibernate.format_sql=true